const proyectos = [
  {
    titulo: "Harry Beck",
    categoria: "Editorial",
    anio: "2026",
    descripcion: "Biografía web sobre el creador del mapa del metro de Londres.",
    imagen: "img/proyectos/harry-beck.jpg",
    alt: "Retrato de Harry Beck",
    enlace: "proyecto-harry-beck.html",
  },
  {
    titulo: "Minimalismo: menos es más",
    categoria: "Editorial",
    anio: "2026",
    descripcion: "Artículo de lectura prolongada sobre el diseño minimalista.",
    imagen: "img/proyectos/minimalismo.jpg",
    alt: "Espacio interior de estilo minimalista",
    enlace: "proyecto-minimalismo.html",
  },
  {
    titulo: "La Velada del Año VI",
    categoria: "Eventos",
    anio: "2026",
    descripcion: "Micrositio promocional para un evento de boxeo ficticio.",
    imagen: "img/proyectos/velada-ring.png",
    alt: "Ring de boxeo preparado para un evento",
    enlace: "proyecto-velada.html",
  },
  {
    titulo: "Ibili Home",
    categoria: "Ecommerce",
    anio: "2026",
    descripcion: "Página principal para una tienda de utensilios de cocina.",
    imagen: "img/proyectos/ibili-cocina.jpg",
    alt: "Utensilios de cocina sobre una mesa",
    enlace: "proyecto-ibili-home.html",
  },
  {
    titulo: "Ibili Catálogo",
    categoria: "Ecommerce",
    anio: "2026",
    descripcion: "Catálogo y ficha de producto responsive para Ibili.",
    imagen: "img/proyectos/ibili-sarten.jpg",
    alt: "Sartén antiadherente del catálogo Ibili",
    enlace: "proyecto-ibili-catalogo.html",
  },
  {
    titulo: "AURA Pilates Studio",
    categoria: "Espacios",
    anio: "2026",
    descripcion: "Sitio web para un estudio de pilates con contenido interactivo.",
    imagen: "img/proyectos/aura-clase.jpg",
    alt: "Sala luminosa de un estudio de pilates",
    enlace: "proyecto-aura.html",
  },
];
